# Generated by Django 4.2 on 2023-05-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyai',
            name='answer_tokens',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historyai',
            name='question_tokens',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
